apiVersion: batch/v1
kind: Job
metadata:
  name: redis-{{ .Release.Name }}
spec:
  parallelism: {{ .Values.parallelism }}
  template:
    metadata:
      name: redis-{{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: redis-{{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["python3", "/daemon.py", "redis-server", "6379", "foo", "--action=sub"]
