apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
spec:
  containers:
    - name: docker
      image: docker
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
