apiVersion: v1
kind: Pod
metadata:
  name: hello-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: hello-nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
