apiVersion: v1
kind: Pod
metadata:
  name: pod-uses-account-hdd-5g
  labels:
    name: storage
spec:
  containers:
    - name: az-c-01
      image: nginx:alpine
      command:
        - /bin/sh
        - -c
        - while true; do echo $(date) >> /mnt/blobdisk/outfile; sleep 1; done
      volumeMounts:
        - mountPath: /mnt/blobdisk
          name: blobdisk01
      resources:
        limits:
          cpu: "128Mi"
          memory: "200m"

  volumes:
    - name: blobdisk01
      persistentVolumeClaim:
        claimName: pv-dd-account-hdd-5g
