apiVersion: v1
kind: Pod
metadata:
  name: nginx-empty-dir-demo
  labels:
    app: nginx-empty-dir-demo
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
  - name: html-updater
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - "while true; do date >> /html/index.html; sleep 10; done"
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - name: html
        mountPath: /html
  volumes:
    - name: html
      emptyDir: {}