apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-configmap
spec:
  selector:
    matchLabels:
      app: node-configmap
  template:
    metadata:
      labels:
        app: node-configmap
    spec:
      volumes:
        - name: app-config-vol
          configMap:
            name: app-settings

      containers:
      - name: node-configmap
        image: node-configmap:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 9000

        volumeMounts:
          - name: app-config-vol
            mountPath: /etc/config

        env:
          - name: ENEMIES
            valueFrom:
              configMapKeyRef:
                name: app-settings
                key: enemies

        envFrom:
          - configMapRef:
              name: app-settings
