version: '2'
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    environment:
      - MASTER=true

  producer:
    container_name: producer
    build: ./redis-producer-c
    depends_on:
      redis:
        condition: service_started

  consumer:
    container_name: consumer
    build: ./redis-consumer-c
    depends_on:
      producer:
        condition: service_started
