version: '2'
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    environment:
      - MASTER=true

  producer:
    container_name: producer
    build: ./redis-producer-c
    depends_on:
      redis:
        condition: service_started

  consumer1:
    restart: on-failure
    container_name: consumer1
    build: ./redis-consumer-c
    depends_on:
      producer:
        condition: service_started

  # consumer2:
  #   restart: on-failure
  #   container_name: consumer2
  #   build: ./redis-consumer-c
  #   depends_on:
  #     producer:
  #       condition: service_started
