apiVersion: v1
kind: Pod
metadata:
  name: busybox-liveness
spec:
  containers:
    - name: busybox-liveness
      image: k8s.gcr.io/busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "50m"
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat 
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5