apiVersion: v1
kind: Pod
metadata:
  name: hello-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: hello-nginx
    image: nginx:alpine
    # Define liveness probe
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
