apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-clusterip
  labels:
    srv: hello-nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: hello-nginx
  ports:
  - port: 8080
    targetPort: 80
