apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-nodeport
  labels:
    srv: hello-nginx-nodeport
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
