apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: {{ .Release.Name }}-{{ .Chart.Name }}
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      command: ["./redis-producer"]
    #   volumeMounts:
    #     - mountPath: /mnt/blobdisk
    #       name: blobdisk01
      resources:
        limits:
          nvidia.com/gpu: 1
