apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: master
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |            
                #!/usr/bin/env bash -e
                #export REDISCLI_AUTH="$REDIS_PASSWORD"

                set_response=$(
                  redis-cli set liveness_test_key "SUCCESS"
                )

                del_response=$(
                    redis-cli del liveness_test_key
                )

                response=$(
                  redis-cli get liveness_test_key
                )

                if [ "$response" != "SUCCESS" ] ; then
                  echo "Unable to get keys, something is wrong"
                  exit 1
                fi               
          initialDelaySeconds: 5
          periodSeconds: 5
