apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: master
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      # livenessProbe:
      #   httpGet:
      #     path: ping
      #     port: 6379
      #   initialDelaySeconds: 15
      #   timeoutSeconds: 2
      #   periodSeconds: 5
      #   failureThreshold: 1
      # readinessProbe:
      #   httpGet:
      #     path: ping
      #     port: 6379
      #   initialDelaySeconds: 3
      #   periodSeconds: 5
      #   failureThreshold: 1
