apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: master
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
