apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - port: 80 # <- This is the localhost port
      targetPort: 8080 # <- This is the container port
